### PR TITLE
RESTService executor

### PR DESCRIPTION
**Pull request by mpawlik**
This set of commits introduces a 'RESTService' executor. Executor function is implemented as a request to remote REST style service with a generic API. The service does the actual work and returns the output. Configuration is supplied through environment variables.

I'm open to any suggestions and requests about this feature.

Please consider using the squash+merge option.

### CODE REVIEW

**Comment by mpawlik** [comment]
I'm assigning @balis as the repository owner and @malawski  as the main author of the feature :)

**Comment by malawski** [comment]
I am OK to merge!

**Comment by balis** [comment]
Looks fine, go ahead with the merge!

**Comment by malawski** [comment]
Merged the executor function used to talk to executors on GCF, AWS Lambda and other cloud functions.

**Pull request merged**
